//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskBranch
    {
        public int id { get; set; }
        public int task_id { get; set; }
        public int branch_id { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
